%--------------------------------------------------------------------------
% Till Habersetzer, 15.07.2025
% Communication Acoustics, CvO University Oldenburg
% till.habersetzer@uol.de 
%
%   Description:
%   This script performs a comprehensive group-level analysis and visualization
%   of pre-computed neural decoding results. It iterates through all specified
%   subjects, conditions and sensor types (MEG, EEG, ear-EEG), loading the 
%   output files generated by the 'training_decoding.m' script.
%
%   The script aggregates key performance metrics, computes grand average 
%   forward models, and generates a series of publication-quality figures 
%   to evaluate both the predictive accuracy and the spatial characteristics 
%   of the trained TRF (Temporal Response Function) models across the dataset.
%
%   Key Analyses & Visualizations:
%   1.  Data Summary: Plots the number of trials during the nested cross-validation
%       used for each subject, condition and sensor in a stacked bar chart.
%   2.  Model Performance Summary: Creates grouped bar charts of the mean
%       correlation scores on held-out test data, comparing the model's
%       performance on sorted vs. shuffled trials. P-values are displayed
%       for each subject.
%   3.  Null Distribution Visualization: Generates detailed swarm charts to
%       visualize the full distribution of correlation scores for sorted trials
%       against the empirically derived null distribution from shuffled trials.
%   4.  Cross-Validation Analysis: Plots the cross-validation curves
%       (both Correlation and Mean-Squared Error) as a function of the
%       regularization parameter (lambda) for all subjects.
%   5.  Regularization Parameter Summary: Visualizes the optimal lambda
%       value chosen for each subject, condition, and sensor type.
%   6.  Individual Forward Models (Topoplots): Visualizes the spatial 
%       distribution of model weights (original or transformed) for each 
%       subject using topographic plots to observe individual spatial patterns.
%   7.  Grand Average Forward Models (Topoplots): Computes peak-normalized 
%       grand averages of the forward models and visualizes the cross-subject 
%       spatial topographies across different conditions and sensor types.
%
%   Input Data & Dependencies:
%   -   Requires a 'settings_decoding.m' file in the MATLAB path.
%   -   Requires the FieldTrip toolbox for topography rendering and 
%       grand-average computation.
%   -   Requires specific sensor layout .mat files for MEG, EEG, and ear-EEG 
%       topographic plotting.
%   -   Expects pre-computed result files generated by 'training_decoding.m',
%       following the filename convention in 'settings.fnames.training_decoder'.
%
%--------------------------------------------------------------------------
close all
clearvars
clc 

%% Import main settings 
%--------------------------------------------------------------------------
settings_decoding

% Display ICA Configuration Feedback
%--------------------------------------------------------------------------
if isfield(settings, 'use_ica') && settings.use_ica
    fprintf('-> CONFIGURATION: ICA is ON (Suffix ''_ica-on'' applied to filenames).\n\n');
else
    fprintf('-> CONFIGURATION: ICA is OFF.\n\n');
end

% Subjects 
subjects = 0:20;
% subjects = 0:10;
n_subj   = length(subjects);

% Conditions
conditions = {'ses-01','ses-02','ses-pooled'}; % ses-01, ses-02, ses-03 -> ses-pooled
n_cond     = length(conditions);

% Select sensors - write into settings
sensors4analysis = {'meg','eeg','ear_eeg'}; % for preprocessing
n_sens           = length(sensors4analysis);

% Analysis parameters
% bpfreq           = [0.5,4];
% decoder_intgrwin = [0,75];
bpfreq           = [0.5,8];
decoder_intgrwin = [0,400];

% Other settings
%--------------------------------------------------------------------------

% Take absolute value of correlation
% apply_abs = true;
apply_abs = false;

% Add paths
%--------------------------------------------------------------------------
addpath(fullfile(settings.path2project,'analysis','helper_functions'))

% Remap sensor labels based on selection
%---------------------------------------
% Initialize output array
sensor_labels = cell(size(sensors4analysis));

for i = 1:length(sensors4analysis)
    switch sensors4analysis{i}
        case 'meg'
            sensor_labels{i} = 'MEG';
        case 'eeg'
            sensor_labels{i} = 'EEG';
        case 'ear_eeg'
            sensor_labels{i} = 'ear-EEG';
        otherwise
            % Fallback for unknown sensors (e.g., make it just uppercase)
            sensor_labels{i} = upper(strrep(sensors4analysis{i}, '_', '-'));
    end
end

%% Import and extract data
%--------------------------------------------------------------------------
subjectnames = cell(1,n_subj);
% accuracy metric
corr_metric = settings.decoding.decoder.corr_metric;
lambda_exp  = settings.decoding.decoder.lambda_exp;
n_lambdas   = length(lambda_exp);
lambdas     = 10.^(lambda_exp );

% Arrays - Audiobook
%--------------------------------------------------------------------------
lambda_vals = zeros(n_subj,n_cond,n_sens); % lambda regularization values used during analysis
cv          = cell(n_subj,n_cond,n_sens);

% All trials and division into training and test trials
n_trials = nan(n_subj,n_cond,n_sens);

% Evaluated on test trials
stats_r_test     = cell(n_subj,n_cond,n_sens,2); % sorted, shuffled
model_p_test     = nan(n_subj,n_cond,n_sens); % p-value: mean correlation value of sorted epochs < shuffled epochs
model_r_test     = nan(n_subj,n_cond,n_sens,2); % 2: mean correlation value of sorted epochs and shuffled epochs
model_r_std_test = nan(n_subj,n_cond,n_sens,2);

% Forward models 
fmodels_all   = cell(2,n_subj,n_cond,n_sens); % original and transformed forward models
fmodels_label = {'original','transformed'};

for sub_idx = 1:n_subj
    subject               = sprintf('sub-%02d',subjects(sub_idx));
    subjectnames{sub_idx} = subject;

    for con_idx = 1:n_cond
        condition = conditions{con_idx};

        for sens_idx = 1:n_sens
            sensor = sensors4analysis{sens_idx};

            % Import trained model on audiobooks
            %--------------------------------------------------------------
            fname = sprintf(settings.fnames.training_decoder,subject,condition,sensor,settings.helper.formatFreqBand(bpfreq),settings.helper.formatIntgrWin(decoder_intgrwin));
            data  = importdata(fullfile(settings.path2decoding_training(subject),fname));  

            cv{sub_idx,con_idx,sens_idx}          = data.cv;
            lambda_vals(sub_idx,con_idx,sens_idx) = data.lambda;

            n_trials(sub_idx,con_idx,sens_idx)       = data.n_trials;

            % Extract forward models
            %-----------------------
            % Initialize as fieldtrip structure for easier managing
            fmodel = data.fmodel;
            
            model2plot        = struct();
            model2plot.label  = fmodel.label;
            if isfield(fmodel,'elec')
                model2plot.grad = fmodel.elec;
            end
            if isfield(fmodel,'grad')
                model2plot.grad = fmodel.grad;
            end
            model2plot.dimord = 'chan_time';

            % (1) original model
            model2plot.time                                 = fmodel.fmodel_orig.t;
            model2plot.avg                                  = squeeze(fmodel.fmodel_orig.w)';
            idx4model                                       = contains(fmodels_label,'original');
            fmodels_all{idx4model,sub_idx,con_idx,sens_idx} = model2plot;
            % (2) transformed model
            model2plot.time                                 = fmodel.fmodel_transformed.t;
            model2plot.avg                                  = squeeze(fmodel.fmodel_transformed.w)';
            idx4model                                       = contains(fmodels_label,'transformed');
            fmodels_all{idx4model,sub_idx,con_idx,sens_idx} = model2plot;

            clear fmodel model2plot idx4model

            % Compute statistics for trained model
            %-------------------------------------
            % test set
            stats_sorted   = data.stats_test.sorted;
            stats_shuffled = data.stats_test.shuffled;
        
            % Metric: Absolute value of correlation
            %--------------------------------------
            if apply_abs

                stats_r_test{sub_idx,con_idx,sens_idx, 1}     = abs(stats_sorted.r); % save null distribution
                stats_r_test{sub_idx,con_idx,sens_idx, 2}     = abs(stats_shuffled.r);

                model_r_test(sub_idx,con_idx,sens_idx, :)     = [mean(abs(stats_sorted.r),"all"); mean(abs(stats_shuffled.r),"all")]; % sorted / shuffled condition
                model_r_std_test(sub_idx,con_idx,sens_idx, :) = [std(abs(stats_sorted.r),0,"all") ./ sqrt(numel(stats_sorted.r));...
                                                                 std(abs(stats_shuffled.r),0,"all") ./ sqrt(numel(stats_shuffled.r))]; % sorted / shuffled condition
                model_p_test(sub_idx,con_idx,sens_idx)        = sum(model_r_test(sub_idx,con_idx,sens_idx,1) < abs(stats_shuffled.r),"all") ./ numel(stats_shuffled.r); % Compute p-value based on null distributin
               
            % Metric: Simple Correlation
            %----------------------------
            else
                
                stats_r_test{sub_idx,con_idx,sens_idx,1}     = stats_sorted.r; % save null distribution
                stats_r_test{sub_idx,con_idx,sens_idx,2}     = stats_shuffled.r;

                model_r_test(sub_idx,con_idx,sens_idx,:)     = [mean(stats_sorted.r,"all"); mean(stats_shuffled.r,"all")]; % sorted / shuffled condition
                model_r_std_test(sub_idx,con_idx,sens_idx,:) = [std(stats_sorted.r,0,"all") ./ sqrt(numel(stats_sorted.r));...
                                                               std(stats_shuffled.r,0,"all") ./ sqrt(numel(stats_shuffled.r))]; % sorted / shuffled condition
                model_p_test(sub_idx,con_idx,sens_idx)       = sum(model_r_test(sub_idx,con_idx,sens_idx,1) < stats_shuffled.r,"all") ./ numel(stats_shuffled.r); % Compute p-value based on null distributin
               
            end
            clear data
    
            fprintf('%s / %s / %s loaded.\n',subject, condition, sensor)

        end % Loop over sensors
    end % Loop over conditions
end % Loop over subjects
fprintf('\nAll trained models loaded.\n')

% Compute grandaverge forward model
%----------------------------------
fmodels_gavg = cell(2,n_cond,n_sens);

for con_idx = 1:n_cond
    for sens_idx = 1:n_sens
        for f_idx = 1:2
            % Additional step: normalize before averaging (scaling
            % differences between subjects)

            models = cellfun(@normalize_avg_field, fmodels_all(f_idx,:,con_idx,sens_idx), 'UniformOutput', false);

            % max(abs(models{20}.avg), [], 'all')
    
            cfg                                  = [];
            fmodels_gavg{f_idx,con_idx,sens_idx} = ft_timelockgrandaverage(cfg, models{:});
            
            clear models
        end % models
    end % sensors
end % conditions

time_vec = fmodels_all{1,1,1,1}.time;

% Load layouts
%-------------
% Use generic EEG-layout from picture
layout_ear_eeg_generic = fullfile('M:\oksima\analysis\layout_ear_eeg','layout-ear_eeg.mat');

% layouts
layouts_eeg     = cell(n_subj,n_cond);
layouts_ear_eeg = cell(n_subj,n_cond);

for sub_idx = 1:n_subj
    dir2load = settings.path2layout(subjectnames{sub_idx});
    for con_idx = 1:n_cond
        condition = conditions{con_idx};

        switch condition
            case {'ses-01','ses-02'}
                % eeg-all
                fname                        = sprintf(settings.fnames.layout,subjectnames{sub_idx},condition,'eeg');
                layout                       = importdata(fullfile(dir2load,fname));
                layouts_eeg{sub_idx,con_idx} = layout;
        
                % ear-eeg
                fname                            = sprintf(settings.fnames.layout,subjectnames{sub_idx},condition,'ear_eeg');
                layout                           = importdata(fullfile(dir2load,fname));
                layouts_ear_eeg{sub_idx,con_idx} = layout;

            % Decision: Use ses-01 for ses-pooled!
            case {'ses-pooled'}
                % eeg-all
                fname                        = sprintf(settings.fnames.layout,subjectnames{sub_idx},'ses-01','eeg');
                layout                       = importdata(fullfile(dir2load,fname));
                layouts_eeg{sub_idx,con_idx} = layout;
        
                % ear-eeg
                fname                            = sprintf(settings.fnames.layout,subjectnames{sub_idx},'ses-01','ear_eeg');
                layout                           = importdata(fullfile(dir2load,fname));
                layouts_ear_eeg{sub_idx,con_idx} = layout;
        end % conditions

    end % sessions
    fprintf('Layouts from %s loaded.\n',subjectnames{sub_idx})
end % subjects
clear dir2load fname layout session
fprintf('All layouts loaded.\n')
       
%% Plot trials across subjects
%--------------------------------------------------------------------------
max_trials = max(n_trials,[],"all");

n_groups         = n_subj;       
n_bars_per_group = 3;  
n_stack_layers   = 2;

bar_labels    = conditions; % Define the labels for the bars within each group
bar_width     = 0.25; 
group_offsets = linspace(-bar_width, bar_width, n_bars_per_group);

colors = [0, 0.4470, 0.7410;         % MATLAB default blue
          0.8500, 0.3250, 0.0980];    % MATLAB default orange

figure('color','white','name','Number of audiobook trials');
colororder(colors);

for sens_idx = 1:n_sens

    % Concat data along third dimension
    data_trials = cat(3, n_trials(:,:,sens_idx));

    subplot(3,1,sens_idx)
    hold on;
    for con_idx = 1:n_bars_per_group
        % Extract data for the i-th bar in each group
        data_for_series = squeeze(data_trials(:,con_idx,:));
        x_positions     = (1:n_groups) + group_offsets(con_idx);
    
        % Plot one series of stacked bars
        bar(x_positions, data_for_series, 'stacked', 'BarWidth', bar_width);
    
        % Add text labels below the bars
        % Calculate a y-position slightly below the axis
        if ismember(sens_idx,[1,2,3])
            y_pos = +5; % Adjust this value as needed
            text(x_positions, repmat(y_pos, 1, n_groups), bar_labels{con_idx}, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'top', ...
                'Rotation', 45, ...
                'FontSize', 10); % Rotate labels to prevent overlap
        end

    end
    hold off;

    if sens_idx == 3
        set(gca,'xtick',1:n_groups,'xticklabels',subjectnames,'xticklabelrotation',45);
        xlabel('Subjects');
    else
        xticks(1:n_groups);
        xticklabels(cell(1,n_subj));
    end

    ylim([0, max_trials+5]);
    yl            = ylabel('Number of trials');
    label_pos     = yl.Extent;
    new_text_x    = label_pos(1) - label_pos(3); % x-pos = left + width
    new_text_y    = label_pos(2) + label_pos(4)/2; % y-pos = bottom + half the height
    text(new_text_x, new_text_y, sensors4analysis{sens_idx}, ...
    'VerticalAlignment', 'middle', ...   % Align vertically
    'HorizontalAlignment', 'left', ...   % Align horizontally
    'FontSize',15, ...
    'Interpreter', 'none', ...
    'FontWeight','bold');      
    ax            = gca;
    ax.FontWeight = 'bold';
    ax.FontSize   = 12;
    box on;
    grid on;
    grid minor;
    if sens_idx == 1
        legend('Training','Test');
    end

end
sgtitle('Audiobook training and test trials across sensors and conditions')

%% Evaluate goodness of individual trained model - Correlation Values
%--------------------------------------------------------------------------

axis_font_size   = 12; 
legend_font_size = 12;
title_font_size  = 16; 

% Set minimum and maximum value across all sensors
ymin  = min(model_r_test,[],'all') - 0.1;
ymax  = max(model_r_test,[],'all') + 0.2;

custom_colors = [0 0.4470 0.7410;
                 0.8500 0.3250 0.0980;   
                 0.9290 0.6940 0.1250];  

for sens_idx = 1:n_sens

    sensor = sensors4analysis{sens_idx};

    figure('color','white','name',sprintf('%s: Audiobook correlation values',sensor)); % new figure for each sensor
 
    % subplot(2,1,1)
    %----------------------------------------------------------------------
    hold on;

    sorted_data   = model_r_test(:,:,sens_idx,1);
    sorted_std    = model_r_std_test(:,:,sens_idx,1);
    
    shuffled_data = model_r_test(:,:,sens_idx,2);
    shuffled_std  = model_r_std_test(:,:,sens_idx,2);

    % Plot sorted data
    %------------------
    b_sorted = bar(sorted_data, 'grouped');
    % Apply custom colors and hatching to the sorted bars
    for con_idx = 1:n_cond
        b_sorted(con_idx).FaceColor = custom_colors(con_idx, :);
        b_sorted(con_idx).FaceAlpha = 0.6;
    end
    h = hatchfill2(b_sorted, 'single', 'HatchAngle', 45, 'HatchColor', 'k', 'HatchLineWidth', 1);
    % Add error bars for the sorted data
    for con_idx = 1:n_cond
        x_coords = b_sorted(con_idx).XEndPoints;
        errorbar(x_coords, sorted_data(:, con_idx), sorted_std(:, con_idx), 'k.', 'LineWidth', 1.5, 'HandleVisibility', 'off');
        
        % Add p-value
        %------------
        y_coords = b_sorted(con_idx).YData;
        for sub_idx = 1:n_subj
            % Place the text labels on the plot
            text(x_coords(sub_idx), y_coords(sub_idx) + 0.1, sprintf("p=%.2f",model_p_test(sub_idx,con_idx,sens_idx)), ...   
            'HorizontalAlignment', 'center', ... % Center the text horizontally
            'VerticalAlignment', 'bottom', ...   % Place text base at the y-coordinate
            'FontSize', 8, ...
            'FontWeight', 'normal');
        end
    end

    % Plot shuffled data
    %-------------------
    b_shuffled = bar(shuffled_data, 'grouped');
    % Apply transparency and a single color to the shuffled bars
    for con_idx = 1:n_cond
        b_shuffled(con_idx).FaceColor = [0.7 0.7 0.7]; % Gray
    end
    % Add error bars for the shuffled data
    for con_idx = 1:n_cond
        x_coords = b_shuffled(con_idx).XEndPoints;
        errorbar(x_coords, shuffled_data(:, con_idx), shuffled_std(:, con_idx), 'k.', 'LineWidth', 1.5, 'HandleVisibility', 'off');
    end

    % Finalize
    %---------
    hold off;
    box on;
    grid on;
    grid minor;
    ylim([ymin, ymax]);
    ax = gca; 
    % Set axis properties
    if apply_abs
        ylabel(sprintf("|r_{%s}|", corr_metric));
    else
        ylabel(sprintf("r_{%s}", corr_metric));
    end
    set(ax,'xtick', 1:n_subj, 'xticklabel', subjectnames, 'XTickLabelRotation', 45);
    ax.FontSize = axis_font_size;
    title('Audiobook: Correlation Values based on test trials', 'FontSize', title_font_size);
    legend([h(1),b_sorted, b_shuffled(1)], [{'Sorted Data'},conditions(:)',{'Shuffled Data'}], 'Location', 'northeast','FontSize', legend_font_size,'Orientation','horizontal');

end

%% Evaluate goodness of individual trained model - Correlation Values + Null-distribution
%--------------------------------------------------------------------------
cmap = distinguishable_colors(n_subj);

% On test trials
%--------------------------------------------------------------------------
for sens_idx = 1:n_sens
    sensor = sensors4analysis{sens_idx};

    figure('color','white','name',sprintf('%s: Null-distribution | test-trials',sensor),'WindowState', 'maximized');
    t            = tiledlayout(n_cond, 1);
    ax_handles   = gobjects(n_cond,1);
    plot_handles = gobjects(4,1); % Pre-allocate array for plot handles
    
    for con_idx = 1:n_cond
        
        condition = conditions{con_idx};
        ax_handles(con_idx) = nexttile; % Capture axes handle
        hold on;
        for sub_idx = 1:n_subj

            % Shuffled data - null distribution
            %----------------------------------
            data2plot = stats_r_test{sub_idx,con_idx,sens_idx,2};
            p1 = swarmchart(sub_idx*ones(1,numel(data2plot)),data2plot(:),30,cmap(sub_idx,:),'Marker','o','MarkerFaceAlpha',0.5,'MarkerEdgeAlpha',0.5);
            % plot mean    
            p2 = plot([sub_idx-0.25, sub_idx+0.25], [model_r_test(sub_idx,con_idx,sens_idx,2),model_r_test(sub_idx,con_idx,sens_idx,2)],'Color',cmap(sub_idx,:),'LineStyle','--','LineWidth', 2,'DisplayName','Threshold');

            % Sorted data
            %------------
            data2plot = stats_r_test{sub_idx,con_idx,sens_idx,1};
            p3 = swarmchart(sub_idx*ones(1,numel(data2plot)),data2plot(:),40,cmap(sub_idx,:),'Marker','*');
            % plot mean    
            p4 = plot([sub_idx-0.25, sub_idx+0.25], [model_r_test(sub_idx,con_idx,sens_idx,1),model_r_test(sub_idx,con_idx,sens_idx,1)],'Color',cmap(sub_idx,:),'LineStyle','-','LineWidth', 2,'DisplayName','Threshold');
            
            if sub_idx == 1
                plot_handles(1) = p1;
                plot_handles(2) = p2;
                plot_handles(3) = p3;
                plot_handles(4) = p4;
            end

            % Add p-value
            %------------
            y_coords = model_r_test(sub_idx,con_idx,sens_idx,1);
            text(sub_idx+0.4, y_coords + 0.01, sprintf("p=%.2f",model_p_test(sub_idx,con_idx,sens_idx)), ...   
            'HorizontalAlignment', 'center', ... % Center the text horizontally
            'VerticalAlignment', 'bottom', ...   % Place text base at the y-coordinate
            'FontSize', 8, ...
            'FontWeight', 'normal');

        end
        hold off;
        
        box on;
        grid on;
        grid minor;
        set(gca, 'FontSize', 12);
        if con_idx == n_cond 
            set(gca,'xtick',1:n_subj,'xticklabel',subjectnames,'XTickLabelRotation',45);
            xlabel('Subjects');
        else
            set(gca,'xtick',1:n_subj,'xticklabel',cell(1,n_subj),'XTickLabelRotation',45);
        end
        if apply_abs
            ylabel(sprintf("|r_{%s}|",corr_metric))
        else
            ylabel(sprintf("r_{%s}",corr_metric))
        end
        title(condition)

        % Link y-axis>: automatically scales them to same value
        linkaxes(ax_handles(:), 'y');

    end
    % Add legend
    lgd              = legend(plot_handles, {'Shuffled trials','Mean shuffled trial','Sorted trials','Mean sorted trials'}, 'Location', 'eastoutside');
    lgd.Title.String = 'Conditions';
    lgd.Layout.Tile  = 'east'; 
    lgd.TextColor    = 'black';  

    title(t, sprintf('%s: Null-distribution | test-trials',sensor), 'FontWeight', 'bold', 'FontSize', 14);
    
end
    
%% Audiobook: Plot cross-validation results - Correlation / MSE
%--------------------------------------------------------------------------

% Correlation
%--------------------------------------------------------------------------
plot_handles = gobjects(n_subj, 1); % Pre-allocate array for plot handles
ax_handles   = gobjects(n_sens, n_cond);

figure('color','white','name','Cross-Validation Results: Correlation','WindowState', 'maximized');
t = tiledlayout(n_sens, n_cond);

for sens_idx = 1:n_sens
    sensor = sensors4analysis{sens_idx};

    for con_idx = 1:n_cond
        condition = conditions{con_idx};
        ax_handles(sens_idx, con_idx) = nexttile; % Capture axes handle

        % Plot data for each subject
        hold on;
        for sub_idx = 1:n_subj
            cv_subj = cv{sub_idx,con_idx,sens_idx};
            n_fold  = size(cv_subj.r,1); % number of folds for cross-validation
            h = errorbar(1:n_lambdas,mean(cv_subj.r,1),std(cv_subj.r,1)/sqrt(n_fold-1),'linewidth',1,'Color',cmap(sub_idx,:));

            % Capture plot handles
            if sens_idx == 1 && con_idx == 1
                plot_handles(sub_idx) = h;
            end

        end
        set(gca,'xtick',1:n_lambdas,'xticklabel',lambda_exp);
        xlim([0,numel(lambdas)+1]);
        hold off;
        box on;
        grid on;
        grid minor;
        if sens_idx == n_sens
            xlabel('Regularization (1\times10^\lambda)');
        end
        if con_idx == 1
            ylabel('Correlation');
        end

        % Add modified labels for conditions and sensors
        %-----------------------------------------------
        if con_idx == 1
            text('Units', 'normalized', ...
                 'Position', [-0.15, 0.5], ... % X, Y position relative to the axes
                 'String', sensor, ...
                 'Rotation', 90, ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'bottom', ...
                 'FontWeight', 'bold', ...
                 'FontSize',15);
        end

        if sens_idx == n_sens
            text('Units', 'normalized', ...
                 'Position', [0.5, -0.25], ...
                 'String', condition, ...
                 'HorizontalAlignment', 'center', ...
                 'FontWeight', 'bold', ...
                 'FontSize',15);
        end

    end

end

% Link y-axis>: automatically scales them to same value
linkaxes(ax_handles(:), 'y');

% Add legend
lgd              = legend(plot_handles, subjectnames, 'Location', 'eastoutside');
lgd.Title.String = 'Subjects';
lgd.Layout.Tile  = 'east'; % This is the key command

title(t, 'Regularization: Cross-Validation Accuracy (Correlation)', 'FontWeight', 'bold', 'FontSize', 14);

% Mean Square Error (MSE)
%--------------------------------------------------------------------------
plot_handles = gobjects(n_subj, 1); % Pre-allocate array for plot handles
ax_handles   = gobjects(n_sens, n_cond);

figure('color','white','name','Cross-Validation Results: Mean Square Error (MSE)','WindowState', 'maximized');
t = tiledlayout(n_sens, n_cond);

for sens_idx = 1:n_sens
    sensor = sensors4analysis{sens_idx};

    for con_idx = 1:n_cond
        condition = conditions{con_idx};
        ax_handles(sens_idx, con_idx) = nexttile; % Capture axes handle

        % Plot data for each subject
        hold on;
        for sub_idx = 1:n_subj
            cv_subj = cv{sub_idx,con_idx,sens_idx};
            n_fold  = size(cv_subj.err,1); % number of folds for cross-validation
            h = errorbar(1:n_lambdas,mean(cv_subj.err,1),std(cv_subj.err,1)/sqrt(n_fold-1),'linewidth',1,'Color',cmap(sub_idx,:));

            % Capture plot handles
            if sens_idx == 1 && con_idx == 1
                plot_handles(sub_idx) = h;
            end

        end

        % Set the y-axis of the current subplot to a log scale.
        set(gca, 'YScale', 'log');

        set(gca,'xtick',1:n_lambdas,'xticklabel',lambda_exp);
        xlim([0,numel(lambdas)+1]);
        hold off;
        box on;
        grid on;
        grid minor;
        if sens_idx == n_sens
            xlabel('Regularization (1\times10^\lambda)');
        end
        if con_idx == 1
            ylabel('MSE');
        end

        % Add modified labels for conditions and sensors
        %-----------------------------------------------
        if con_idx == 1
            text('Units', 'normalized', ...
                 'Position', [-0.15, 0.5], ... % X, Y position relative to the axes
                 'String', sensor, ...
                 'Rotation', 90, ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'bottom', ...
                 'FontWeight', 'bold', ...
                 'FontSize',15);
        end

        if sens_idx == n_sens
            text('Units', 'normalized', ...
                 'Position', [0.5, -0.25], ...
                 'String', condition, ...
                 'HorizontalAlignment', 'center', ...
                 'FontWeight', 'bold', ...
                 'FontSize',15);
        end

    end

end

% Link y-axis>: automatically scales them to same value
linkaxes(ax_handles(:), 'y');

% Add legend
lgd              = legend(plot_handles, subjectnames, 'Location', 'eastoutside');
lgd.Title.String = 'Subjects';
lgd.Layout.Tile  = 'east'; % This is the key command

title(t, 'Regularization: Cross-Validation Accuracy (MSE)', 'FontWeight', 'bold', 'FontSize', 14);

%% Audiobook: Plot regularization parameters
%--------------------------------------------------------------------------
cond_markers = {'o','square','diamond'};
plot_handles = gobjects(n_cond,1); % Pre-allocate array for plot handles
ax_handles   = gobjects(n_sens,1);

figure('color','white','name','Regularization Values','WindowState', 'maximized');
t = tiledlayout(n_sens, 1);

for sens_idx = 1:3

    sensor = sensors4analysis{sens_idx};
    ax_handles(sens_idx) = nexttile; % Capture axes handle
    hold on;
    for sub_idx = 1:n_subj
        for con_idx = 1:n_cond
            h = plot(sub_idx,log10(lambda_vals(sub_idx,con_idx,sens_idx)),cond_markers{con_idx},'LineWidth', 2,'Color',cmap(sub_idx,:));

            % Capture plot handles
            if sens_idx == 1 && sub_idx == 1
                plot_handles(con_idx) = h;
            end

        end

    end
    hold off;

    set(gca, 'FontSize', 12); 
    set(gca,'xtick',1:n_subj,'xticklabel',subjectnames,'XTickLabelRotation',45);
    xlim([0,n_subj+1]);
    ylim([lambda_exp(1),lambda_exp(end)]);
    hold off;
    box on;
    grid on;
    grid minor;
    if sens_idx == n_sens
        xlabel('Subjects');
    end
    ylabel('Regularization (1\times10^\lambda)')

    title(sensor)
end

% Link y-axis>: automatically scales them to same value
linkaxes(ax_handles(:), 'y');

% Add legend
lgd              = legend(plot_handles, conditions, 'Location', 'eastoutside');
lgd.Title.String = 'Conditions';
lgd.Layout.Tile  = 'east'; 
lgd.TextColor    = 'black';  

title(t, 'Regularization Values', 'FontWeight', 'bold', 'FontSize', 14);

%% Visualize forward modells - Topoplots - all subjects
%--------------------------------------------------------------------------

% Select which forward model to plot
fmodel2plot = 'original';
% fmodel2plot = 'transformed';

idx4model = find(contains(fmodels_label,fmodel2plot));

% Select timewindow for plotting
% timewin2plot = [1,17]; % time_vec(1):time_vec(6)
timewin2plot = [1,numel(time_vec)]; % time_vec(1):time_vec(6)

% Select MEG channel subset for plotting
sens2plot = 'meg'; % 'meg','mag','grad'

switch sens2plot
    case 'mag'
        layout_meg = 'neuromag306mag_helmet.mat';
    case 'grad'
        layout_meg = 'neuromag306planar_helmet.mat';
    case 'meg'
        layout_meg = 'neuromag306all_helmet.mat';
end

for sub_idx = 1:n_subj % Loop over subjects
    
    subject = subjectnames{sub_idx};
    figure('color','white','name',sprintf("%s: Forward model weights (%s)",subject,fmodel2plot),'WindowState', 'maximized');
    % Pre-allocate ax_handles array
    ax_handles  = gobjects(n_sens, n_cond);
 
    for sens_idx = 1:n_sens
        sensor = sensors4analysis{sens_idx};

        % Global axis limits
        %-------------------
        d1       = cellfun(@(x) mean(x.avg(:,timewin2plot(1):timewin2plot(2)),2) , fmodels_all(idx4model,sub_idx,:,sens_idx), 'UniformOutput', false);
        ylim_min = min(vertcat(d1{:}),[],"all"); 
        ylim_max = max(vertcat(d1{:}),[],"all");
        
        for con_idx = 1:n_cond
            condition = conditions{con_idx};
            plot_idx = (sens_idx - 1) * n_cond + con_idx;  
            ax_handles(sens_idx, con_idx) = subplot(n_sens,n_cond,plot_idx); % Capture axes handle

            % Select layout
            switch sensor
                case 'meg'
                    layout = layout_meg;
                case 'eeg'
                    layout = layouts_eeg{sub_idx,con_idx};
                case 'ear_eeg'
                    %layout = layouts_ear_eeg{sub_idx,con_idx};
                    layout = layout_ear_eeg_generic;
                otherwise
                    error('Unexpected sensor (%s)!',sensor)
            end

            cfg             = [];
            cfg.xlim        = [time_vec(timewin2plot(1)),time_vec(timewin2plot(2))];
            cfg.zlim        = [ylim_min,ylim_max];
            cfg.comment     = 'no';
            cfg.layout      = layout;
            cfg.interactive = 'no';
            cfg.figure      = gca; %ax_handles(sens_idx, con_idx); 
            cfg.colorbar    = 'no'; % Turn off individual colorbars
            ft_topoplotER(cfg, fmodels_all{idx4model,sub_idx,con_idx,sens_idx});
            colormap(bluewhitered)
    
            % Add modified labels for conditions and sensors
            %-----------------------------------------------
            if con_idx == 1
                text('Units', 'normalized', ...
                     'Position', [-0.15, 0.5], ... % X, Y position relative to the axes
                     'String', sensor, ...
                     'Rotation', 90, ...
                     'HorizontalAlignment', 'center', ...
                     'VerticalAlignment', 'bottom', ...
                     'FontWeight', 'bold', ...
                     'Interpreter', 'none', ...
                     'FontSize',15);
            end
    
            if sens_idx == n_sens
                text('Units', 'normalized', ...
                     'Position', [0.5, -0.25], ...
                     'String', condition, ...
                     'HorizontalAlignment', 'center', ...
                     'FontWeight', 'bold', ...
                     'Interpreter', 'none', ...
                     'FontSize',15);
            end

        end % Loop over conditions

        % Add a single colorbar for the entire row
        %-----------------------------------------
        last_ax_pos = get(ax_handles(sens_idx, n_cond), 'Position');

        % Define position for the new colorbar's axes [left, bottom, width, height]
        cb_pos = [last_ax_pos(1) + last_ax_pos(3) + 0.01, ... % Position it to the right of the last plot
                  last_ax_pos(2), ...                         
                  0.015, ...                                  % Make it thin
                  last_ax_pos(4)];                            % Same height as the plots

        % Create a new axes specifically for the colorbar
        cb_ax = axes('Position', cb_pos);

        % Add the colorbar and set its scale to match the plots
        cb = colorbar(cb_ax); 
        clim(cb_ax, [ylim_min, ylim_max]);
        axis(cb_ax, 'off');
        % Set the colorbar label using its own 'Label' property
        cb.Label.String     = 'Model Weights';
        cb.Label.FontSize   = 12;

    end % Loop over sensors

    sgtitle(sprintf("%s: Forward model weights (%s)",subject,fmodel2plot))
end % Loop over subjects   

%% Visualize forward modells - Topoplots - Grandaverage
%--------------------------------------------------------------------------
% Notes: Averaging across participants is questionable due to differen head
% positions inside MEG and different Cap Fit (across participants AND
% sessions -> thats why pooling is critical)

% Select which forward model to plot
fmodel2plot = 'original';
% fmodel2plot = 'transformed';

idx4model   = find(contains(fmodels_label,fmodel2plot));

% Select conditions
%------------------
conditions2plot = conditions;
% conditions2plot = {'ses-pooled'};
% conditions2plot = {'ses-01'};

% Select timewindow for plotting
% timewin2plot = [1,17]; % time_vec(1):time_vec(6)
timewin2plot = [1,numel(time_vec)]; % time_vec(1):time_vec(6)

% Select MEG channel subset for plotting
sens2plot = 'meg'; % 'meg','mag','grad'

switch sens2plot
    case 'mag'
        layout_meg = 'neuromag306mag_helmet.mat';
    case 'grad'
        layout_meg = 'neuromag306planar_helmet.mat';
    case 'meg'
        layout_meg = 'neuromag306all_helmet.mat';
end

cond_idxs   = find(ismember(conditions, conditions2plot));
n_cond2plot = length(conditions2plot);

figure('color','white','name',sprintf("Gavg: Forward model weights (%s)",fmodel2plot), 'WindowState', 'maximized');
% Pre-allocate ax_handles array
ax_handles  = gobjects(n_cond2plot, n_sens);

for sens_idx = 1:n_sens
    sensor = sensor_labels{sens_idx};
   
    % Global axis limits
    %-------------------
    d1        = cellfun(@(x) mean(x.avg(:,timewin2plot(1):timewin2plot(2)),2) , fmodels_gavg(idx4model, cond_idxs, sens_idx), 'UniformOutput', false);
    ylim_min  = min(vertcat(d1{:}),[],"all"); 
    ylim_max  = max(vertcat(d1{:}),[],"all");
    limit_val = max(abs([ylim_min, ylim_max]));
    
    for con_idx2 = 1:n_cond2plot
        condition = conditions2plot{con_idx2};
        con_idx   = cond_idxs(con_idx2);
        
        plot_idx = (con_idx2 - 1) * n_sens + sens_idx;  
        ax_handles(con_idx2, sens_idx) = subplot(n_cond2plot ,n_sens, plot_idx); % Capture axes handle

        % Select layout
        switch sensor
            case 'MEG'
                layout = layout_meg;
            case 'EEG'
                % fix it
                layout = layouts_eeg{1,1};
            case 'ear-EEG'
                %layout = layouts_ear_eeg{sub_idx,con_idx};
                layout = layout_ear_eeg_generic;
            otherwise
                error('Unexpected sensor (%s)!',sensor)
        end

        cfg             = [];
        cfg.xlim        = [time_vec(timewin2plot(1)),time_vec(timewin2plot(2))];
        cfg.zlim        = [-limit_val, limit_val];
        cfg.comment     = 'no';
        cfg.layout      = layout;
        cfg.interactive = 'no';
        cfg.figure      = gca; %ax_handles(sens_idx, con_idx); 
        cfg.colorbar    = 'no'; % Turn off individual colorbars
        ft_topoplotER(cfg, fmodels_gavg{idx4model, con_idx, sens_idx});
        colormap(bluewhitered)

        % Add modified labels for conditions and sensors
        %-----------------------------------------------
        if sens_idx == 1
            text('Units', 'normalized', ...
                 'Position', [-0.15, 0.5], ... % X, Y position relative to the axes
                 'String', condition, ...
                 'Rotation', 90, ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'bottom', ...
                 'FontWeight', 'bold', ...
                 'Interpreter', 'none', ...
                 'FontSize',15);
        end

        if con_idx2 == 1
            title(sensor_labels{sens_idx}, 'FontSize', 15)
        end

    end % Loop over conditions

    % Add a single colorbar for the entire row
    %-----------------------------------------
    first_ax_pos = get(ax_handles(1, sens_idx), 'Position');
    last_ax_pos  = get(ax_handles(n_cond2plot, sens_idx), 'Position');

    % Calculate full width (from start of first plot to end of last plot)
    full_width = (last_ax_pos(1) + last_ax_pos(3)) - first_ax_pos(1);
    
    % Define position: [left, bottom, width, height]
    % We place it below 'last_ax_pos(2)' by subtracting a small offset
    cb_pos = [first_ax_pos(1), ...           
              last_ax_pos(2) - 0.02, ...     
              full_width, ...                
              0.025];                        
    
    % Create the axes and the horizontal colorbar
    cb_ax = axes('Position', cb_pos);
    cb    = colorbar(cb_ax, 'Location', 'southoutside', 'Orientation', 'horizontal'); 
    
    % Sync limits and clean up
    clim(cb_ax, [-limit_val, limit_val]);
    axis(cb_ax, 'off');
    
    % Set labels
    cb.Label.String   = 'Model Weights';
    cb.Label.FontSize = 12;

end % Loop over sensors

sgtitle(sprintf("Gavg: Forward model weights (%s)",fmodel2plot), 'FontWeight', 'bold')

% Plot timecourses
%-----------------
% con_idx  = 3;
% sens_idx = 2;
% 
% figure
% cfg             = [];
% cfg.comment     = 'no';
% % cfg.layout      = layout_meg;
% cfg.layout      = layouts_eeg{20,1};
% ft_multiplotER(cfg, fmodels_gavg{idx4model, con_idx, sens_idx});


%% Functions
%--------------------------------------------------------------------------

function output_struct = normalize_avg_field(input_struct)
    % Start with a copy of the original struct
    output_struct = input_struct;
    
    % Get the data and normalization factor
    avg_data    = input_struct.avg;
    norm_factor = max(abs(avg_data(:)));
    
    % Update the field, avoiding division by zero
    if norm_factor > 0
        output_struct.avg = avg_data / norm_factor;
    end
end
