function preprocessing_meeg_olsa_decoding(settings,subject,session)
%--------------------------------------------------------------------------
% Till Habersetzer, 06.07.2025
% Communication Acoustics, CvO University Oldenburg
% till.habersetzer@uol.de 
% 
% Description:
%   Performs subject-level preprocessing of combined M/EEG data from the
%   Oldenburg Sentence Test (OLSA) task. This function prepares the data
%   for neural decoding by creating synchronized, trial-based epochs of
%   neural activity and the corresponding auditory stimulus envelopes.
%
%   It handles different sensor types (MEG, EEG, ear-EEG, biochannels) and 
%   preprocessing stages, and critically, it enriches the neural data with 
%   detailed event metadata (e.g., SNR, intelligibility) extracted from 
%   BIDS event files.
%
%   Notably, this script is designed for a hybrid Python-to-MATLAB workflow: 
%   It ingests data previously preprocessed in MNE-Python (e.g., MaxFiltered 
%   or ICA-cleaned .fif files) and dynamically imports bad channel metadata 
%   generated by PyPrep (via JSON) to apply FieldTrip's spherical spline 
%   interpolation prior to spatial re-referencing.
%
% Key Steps:
%   1.  **Select & Validate Sensors:** Extracts the target sensors. For EEG,
%       it enforces a strict validation of exactly 76 unique cap + ear sensors.
%   2.  **Load Neural Data:** Selects and loads the appropriate continuous
%       M/EEG data file based on the specified subject, session, and
%       preprocessing stage (e.g., maxfiltered, ICA-cleaned).
%   3.  **Define Trials & Metadata:** Defines trials based on BIDS events,
%       applies latency correction (if enabled), and extracts critical metadata 
%       for each trial (SNR, intelligibility score, and stimulus audio file).
%   4.  **Filter:** Applies a band-pass filter to the continuous data to 
%       prevent edge artifacts during epoching.
%   5.  **Bad Channel Interpolation (EEG only):** If operating on non-ICA data, 
%       reads Python-generated JSON metadata to identify bad channels and 
%       repairs them using spherical spline interpolation (Perrin et al., 1989).
%   6.  **Re-referencing:** Applies sensor-specific referencing:
%       - Cap EEG: Common Average Reference (CAR) across all channels.
%       - Ear-EEG: Independent CAR for left and right ear channels.
%   7.  **Epoching & Resampling:** Segments the continuous data into trials 
%       with pre- and post-stimulus padding, handles missing data exceptions, 
%       and downsamples each epoch to the target frequency.
%   8.  **Construct Audio Trials:** Loads the pre-processed auditory envelopes
%       and speech detection vectors, then constructs the corresponding audio
%       trial sequence based on the subject's unique stimulus playlist.
%   9.  **Synchronize Lengths:** Performs a final sample-by-sample length
%       matching of each neural and audio epoch to ensure perfect temporal alignment.
%   10. **Save Output:** Saves a single .mat file for the specified sensor
%       type, containing a results struct with the cleaned data and all
%       relevant metadata.
%
% Syntax:
%   preprocessing_meeg_olsa_decoding(settings, subject, session)
%
% Inputs:
%   settings (struct):      A structure containing all analysis paths
%                           (e.g., BIDS root, derivatives, JSON metadata) 
%                           and parameters (e.g., filter settings, epoch padding).
%   subject (char/string):  The subject identifier (e.g., 'sub-01').
%   session (char/string):  The session identifier (e.g., 'ses-01').
%
% Outputs:
%   (None directly, saves a file to disk)
%   - A .mat file is saved to the subject's preprocessing directory, with a
%     filename dynamically generated based on subject, session, sensor and 
%     frequency band. The file contains a 'results' struct with the following 
%     key fields:
%       .epochs_neuro:           Preprocessed neural data (FieldTrip struct).
%       .epochs_audio:           Synchronized audio envelope for each trial.
%       .epochs_audio_detection: Synchronized speech detection vector.
%       .event_description:      Metadata struct with SNR, intelligibility, etc.
%       .settings:               The settings structure used for preprocessing.
%
%--------------------------------------------------------------------------

%% Script settings 
%--------------------------------------------------------------------------

% Taskname
task = 'olsa';

% Get selected sensors
cfg_sensors      = settings.cfg_sensors; % used for channel selection
sensors4analysis = settings.analysis.sensors;
n_sens           = length(sensors4analysis);

% Runs
runs   = [1,2,3];
n_runs = length(runs);

% Preprocessing settings
%--------------------------------------------------------------------------
use_maxfilter            = settings.use_maxfilter; % check whether maxfiltered data should be analyzed
use_ica                  = settings.use_ica; % check whether ica preprocessed data should be analyzed
apply_latency_correction = settings.apply_latency_correction; % Latency Correction
audio_latency            = settings.audio_latency;
interpolate_bad_channel  = settings.interpolate_bad_channel; % only affects EEG

% Filter settings
filtertype = settings.decoding.filtertype; % windowed sinc type I linear phase FIR filter
bpfreq     = settings.decoding.bpfreq; % meg + audio

fs_down    = settings.decoding.fs_down; % Downsampling frequency
fs_neuro   = settings.decoding.fs_neuro; % MEG sampling frequency
prestim    = settings.decoding.olsa.prestim; % Epoch length for olsa trials
poststim   = settings.decoding.olsa.poststim;

%% Preprocessing 
%--------------------------------------------------------------------------

% Loop over different sensors
%--------------------------------------------------------------------------
for sens_idx = 1:n_sens % Loop over sensors / channels

    % Initialize data
    epochs_neuro           = cell(1,n_runs);
    epochs_audio           = cell(1,n_runs);
    epochs_audio_detection = cell(1,n_runs);
    snr_data               = cell(1,n_runs);
    intelli_data           = cell(1,n_runs);
    playlist_data          = cell(1,n_runs);
    mapping_epochs         = zeros(n_runs,2);
    mapping_labels         = cell(1,n_runs);

    f_idx         = 1; % file counter
    epoch_counter = 0; % epoch counter

    sensor = sensors4analysis{sens_idx};
    % MEG
    if strcmp(sensor, 'meg')
        channel = sensor;
    % EEG
    elseif strcmp(sensor, 'eeg')
        channel = unique([cfg_sensors.cap_eeg(:); cfg_sensors.ear_eeg.both(:)]);
        assert(numel(channel) == 76, 'Expected exactly 76 unique sensors, got %d', numel(channel));
    % Ear-EEG
    elseif strcmp(sensor, 'ear_eeg')
        channel = cfg_sensors.ear_eeg.both;
    % Biochannels
    elseif strcmp(sensor, 'biochannels')
        channel = settings.cfg_sensors.biochannels;
    else
        error('Unexpected sensor type: %s', sensor);
    end

    for run_idx = 1:n_runs % loop over files

        run = sprintf('run-0%i',runs(run_idx));

        % Define datapath
        %----------------
        if use_maxfilter && use_ica
            rawdata_path = fullfile(settings.path2ica(subject));
            filename     = sprintf('%s_%s_task-%s_%s_proc-ica_meg.fif',subject,session,task,run);
            data_path    = fullfile(rawdata_path,filename);

        elseif use_maxfilter && ~use_ica
            rawdata_path = fullfile(settings.path2derivatives,subject,'maxfilter');
            % Use movement-corrected data first
            if strcmp(subject,'sub-00')
                filename = sprintf('%s_%s_task-%s_%s_proc-tsss_meg.fif',subject,session,task,run); 
            else  
                filename = sprintf('%s_%s_task-%s_%s_proc-tsss-mc_meg.fif',subject,session,task,run); 
            end
            data_path    = fullfile(rawdata_path,filename);
  
        else
            rawdata_path = fullfile(settings.path2bids,subject,session,'meg');
            filename     = sprintf('%s_%s_task-%s_%s_meg.fif',subject,session,task,run);
            data_path    = fullfile(rawdata_path,filename);
            % badchannels  = settings.badchannels; 
            
        end

        % use always bids data for events
        event_path = fullfile(settings.path2bids,subject,session,'meg',sprintf('%s_%s_task-%s_%s_meg.fif',subject,session,task,run));

        % Process data if it exists
        if isfile(data_path)
        
            %% Define trials
            %---------------
            % Requires BIDS annotated events (especially the duration column)
            cfg                     = [];
            cfg.trialfun            = 'my_trialfun_olsa'; 
            cfg.dataset             = event_path; % path should always point to original bids-path
            cfg.trialdef.prestim    = prestim;
            cfg.trialdef.poststim   = poststim;
            cfg                     = ft_definetrial(cfg);
        
            trl = cfg.trl;
 
            % Add event_description
            %----------------------    
            snr_data{run_idx}     = trl(:,6);
            intelli_data{run_idx} = trl(:,7);

            % Load events.tsv file to get additional event information
            event                  = readtable(strrep(event_path,'meg.fif','events.tsv'),'FileType', 'text', 'Delimiter', '\t');
            playlist_data{run_idx} = event.stim_file;
            clear event

            %% Add latency correction 
            %------------------------
            if apply_latency_correction
                trl(:,1:2) = trl(:,1:2) + round(audio_latency*1000); % in samples
            end

            %% Filter continuous data to avoid edge artifacts
            %------------------------------------------------
            cfg              = [];
            cfg.channel      = channel; 
            cfg.dataset      = data_path;
            cfg.bpfilter     = 'yes';
            cfg.bpfilttype   = filtertype;
            cfg.bpfreq       = bpfreq;
            cfg.plotfiltresp = 'no';
            data             = ft_preprocessing(cfg); 
        
            if ~isequal(data.fsample,fs_neuro)
                error('Unexpected sampling frequency for meg recordings (%i)!',data.fsample)
            end

            % plot spectrum
            %--------------
            % cfg         = [];
            % cfg.output  = 'pow';
            % cfg.channel = channel;
            % cfg.method  = 'mtmfft';
            % cfg.taper   = 'hanning';
            % cfg.foi     = 0:100;    
            % spectr      = ft_freqanalysis(cfg,data);   
            % 
            % figure
            % plot(spectr.freq,db(spectr.powspctrm(:,:)))
            % xlabel('f / Hz')    
            % xlim([0,80])

            %% Apply bad channel interpolation
            %--------------------------------------------------------------
	        % - This should only be applied to maxfiltered or raw data, as 
            %   ICA-preprocessed data has already been interpolated in Python.
            % - This step exclusively affects EEG channels.
            % - Requires the list of bad channels detected during the 
            %   ICA pipeline and stored in a JSON metadata file.

            if ismember(sensor, {'eeg', 'ear_eeg'}) && interpolate_bad_channel && ~use_ica
    
                % Import bad channels from Python JSON metadata
                %----------------------------------------------
                fname2load   = fullfile(settings.path2ica(subject), sprintf('%s_metadata_proc-ica_meg.json', subject));
                jsonText     = fileread(fname2load);
                metadata_ica = jsondecode(jsonText);
                
                % Extract bad channels 
                % (Replacing hyphens with underscores to match valid MATLAB struct fields)
                session_field = strrep(session, '-', '_');
                fname_field   = strrep(sprintf('%s_%s', task, run), '-', '_');
                bad_channels  = metadata_ica.(session_field).bad_channels.(fname_field);
                 
                % Interpolate bad channels using spherical splines
                %-------------------------------------------------
                if ~isempty(bad_channels)
                    cfg            = [];
                    cfg.badchannel = intersect(channel, bad_channels); % bad channels that do occur
                    cfg.method     = 'spline';
                    cfg.senstype   = 'eeg';
                    data           = ft_channelrepair(cfg, data);
                end
                clear fname2load jsonText metadata_ica session_field fname_field bad_channels
            end

            %% Managing EEG channel reference
            %--------------------------------
            if strcmp(sensor,'eeg')
                
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; % this is the default
                cfg.refchannel = 'all'; % average is computed over the channels specified in cfg.refchannel
                data           = ft_preprocessing(cfg,data);

            elseif strcmp(sensor,'ear_eeg')
                % use avg ref instead of individual channels to make it
                % more robust
    
                % Left channels
                %--------------
                cfg         = []; 
                cfg.channel = cfg_sensors.ear_eeg.left;
                data_left   = ft_selectdata(cfg,data);
    
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; 
                % cfg.refchannel = 'EEG073'; 
                cfg.refchannel = 'all';
                data_left      = ft_preprocessing(cfg,data_left);
    
                % Right channels
                %---------------
                cfg         = []; 
                cfg.channel = cfg_sensors.ear_eeg.right;
                data_right  = ft_selectdata(cfg,data);
    
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; 
                % cfg.refchannel = 'EEG074'; 
                cfg.refchannel = 'all';
                data_right     = ft_preprocessing(cfg,data_right);
    
                % Append data
                %------------
                cfg  = [];
                data = ft_appenddata(cfg,data_left,data_right);
    
                % Remove references
                %------------------
                % idx                = contains(channels,{'EEG073','EEG074'});
                % channels_both      = channels;
                % channels_both(idx) = [];
                % 
                % cfg         = [];
                % cfg.channel = channels_both;
                % data        = ft_selectdata(cfg,data);
                   
                clear data_left data_right 
            end

            %% Epoch data
            %------------
            cfg     = [];
            cfg.trl = trl;  
            epoch   = ft_redefinetrial(cfg,data);
            clear data

            % Exception! Fill nan-data for sub-05 / run-02 with 0s OR
            % remove trial (For 0.5 s poststim, 389 ms of data are missing...)
            if strcmp(subject,'sub-05') && run_idx == 2
                epoch.trial{end} = fillmissing(epoch.trial{end},'constant',0);
                epoch.time{end}  = fillmissing(epoch.time{end},'constant',0);
            end

            % Count epochs
            n_epochs                = length(epoch.trial);
            mapping_epochs(f_idx,:) = [epoch_counter+1,epoch_counter + n_epochs];
            epoch_counter           = epoch_counter + n_epochs;
            mapping_labels{f_idx}   = sprintf('%s_task-%s_%s',session,task,run);

            %% Downsampling
            %--------------
            cfg                 = [];
            cfg.resamplefs      = fs_down;
            cfg.detrend         = 'no';
            epochs_neuro{f_idx} = ft_resampledata(cfg,epoch);
            clear epoch

            %% Import audio data
            %--------------------------------------------------------------
            fname           = sprintf(settings.fnames.audio_olsa, settings.helper.formatFreqBand(bpfreq));     
            audio_envelopes = importdata(fullfile(settings.path2derivatives,'stimuli',fname));
            
            % Loop over playlist and generate epochs_audio
            %---------------------------------------------
            sentences           = cell(1,n_epochs);
            sentences_detection = cell(1,n_epochs);
        
            for trl_idx = 1:n_epochs
                fname_audio                  = playlist_data{run_idx}{trl_idx};
                [~, base_name, ~]            = fileparts(fname_audio);  
                sentences{trl_idx}           = audio_envelopes.(sprintf('envelope_%s',base_name));
                sentences_detection{trl_idx} = audio_envelopes.(sprintf('audio_detection_%s',base_name));
            end

            epochs_audio{run_idx}           = sentences;
            epochs_audio_detection{run_idx} = sentences_detection;
            clear sentences sentences_detection

        end % file exists

        % Increment counter
        f_idx = f_idx + 1;

    end % Loop over runs

    %% Append data over runs
    %----------------------------------------------------------------------
    % Keep only non-empty cells in case runs are missing
    nonEmptyIdx    = ~cellfun('isempty',mapping_labels);
    mapping_epochs = mapping_epochs(nonEmptyIdx,:);
    mapping_labels = mapping_labels(nonEmptyIdx);

    % Append MEG recordings
    cfg                = [];
    cfg.keepsampleinfo = 'no'; 
    epochs_neuro       = ft_appenddata(cfg, epochs_neuro{:});

    % Append Audio recordings
    epochs_audio           = [epochs_audio{:}];
    epochs_audio_detection = [epochs_audio_detection{:}];

    % Append rest
    snr_data      = vertcat(snr_data{:});
    intelli_data  = vertcat(intelli_data{:});
    playlist_data = vertcat(playlist_data{:});

    % Create event description
    %-------------------------
    event_description                = struct();
    event_description.snr_data       = snr_data;
    event_description.intelli_data   = intelli_data;
    event_description.playlist_data  = playlist_data;
    event_description.mapping_epochs = mapping_epochs;
    event_description.mapping_labels = mapping_labels;

    %% Match durations of neuro and audio epochs
    %----------------------------------------------------------------------
    n_neuro = length(epochs_neuro.trial);
    n_audio = length(epochs_audio);
    
    if ~isequal(n_neuro,n_audio)
        error('Unexpected number of audio trials (%i) and neuro trials (%s)!',n_audio,n_neuro)
    end
    
    check_length = zeros(n_audio,2);
    for trl_idx = 1:n_neuro
        check_length(trl_idx,1) = size(epochs_neuro.trial{trl_idx},2);
        check_length(trl_idx,2) = length(epochs_audio{trl_idx});
    end
    
    % Sanity Check: Distance is bigger than 1 sample
    if any(abs(check_length(:,1)-check_length(:,2))>1)
        error("Trial durations don't match")
    end

    % Get index of minimum length for each trial
    [min_durs,~] = min(check_length,[],2);
    
    % Match length of trials
    for trl_idx = 1:n_neuro
        min_dur                         = min_durs(trl_idx);
        epochs_neuro.trial{trl_idx}     = epochs_neuro.trial{trl_idx}(:,1:min_dur);
        epochs_neuro.time{trl_idx}      = epochs_neuro.time{trl_idx}(1:min_dur);
        epochs_audio{trl_idx}           = epochs_audio{trl_idx}(1:min_dur);
        epochs_audio_detection{trl_idx} = epochs_audio_detection{trl_idx}(1:min_dur);
    end   

    %% Save results
    %--------------
    dir2save = settings.path2decoding_preprocessing(subject);
    if ~exist(dir2save,'dir')
        mkdir(dir2save)
    end
    fname = sprintf(settings.fnames.preprocessed_olsa,subject,session,sensor,settings.helper.formatFreqBand(bpfreq));
    
    results                        = struct;
    results.settings               = settings;
    results.epochs_neuro           = epochs_neuro;
    results.epochs_audio           = epochs_audio;
    results.epochs_audio_detection = epochs_audio_detection;
    results.event_description      = event_description;
    
    save(fullfile(dir2save,fname),'results','-v7.3'); 
    fprintf("\n%s from %s saved.\n",fname,subject)

end % loop over sensors

end % end of function