function preprocessing_meeg_audiobooks_decoding(settings,subject,session)
%--------------------------------------------------------------------------
% Till Habersetzer, 05.07.2025
% Communication Acoustics, CvO University Oldenburg
% till.habersetzer@uol.de 
%
% Description:
%   Performs subject-level preprocessing of combined M/EEG data from a
%   continuous audiobook listening task. This function is a core component
%   of the neural decoding pipeline, creating synchronized epochs of neural
%   activity and the corresponding auditory stimulus envelopes.
%
%   The function handles different sensor types (MEG, EEG, ear-EEG and 
%   biochannels), data processing stages (raw, maxfiltered, ICA), and 
%   performs crucial data cleaning and alignment steps to ensure all trials 
%   are of uniform length and perfectly synchronized across modalities. 
%
%   Notably, this script is designed for a hybrid Python-to-MATLAB workflow: 
%   It ingests data previously preprocessed in MNE-Python (e.g., MaxFiltered 
%   or ICA-cleaned .fif files) and dynamically imports bad channel metadata 
%   generated by PyPrep (via JSON) to apply FieldTrip's spherical spline 
%   interpolation prior to spatial re-referencing.
%
% Key Steps:
%   1.  **Select & Validate Sensors:** Extracts the target sensors. For EEG,
%       it enforces a strict validation of exactly 76 unique cap + ear sensors.
%   2.  **Load Neural Data:** Selects and loads the appropriate continuous
%       M/EEG data file based on the specified subject, session, and
%       preprocessing stage (e.g., maxfiltered, ICA-cleaned).
%   3.  **Define & Filter Epochs:** Defines trials of a fixed duration
%       (e.g., 60s) using BIDS events, applies latency correction (if enabled), 
%       and band-pass filters the continuous data.
%   4.  **Bad Channel Interpolation (EEG only):** If operating on non-ICA data, 
%       reads Python-generated JSON metadata to identify bad channels and 
%       repairs them using spherical spline interpolation (Perrin et al., 1989).
%   5.  **Re-referencing:** Applies sensor-specific referencing:
%       - Cap EEG: Common Average Reference (CAR) across all channels.
%       - Ear-EEG: Independent CAR for left and right ear channels.
%   6.  **Epoching & Resampling:** Segments the continuous data into trials, 
%       adjusts the time axes, and downsamples to the target frequency (e.g., 64 Hz).
%   7.  **Synchronize with Audio:** Loads the corresponding pre-processed
%       audio envelope data and performs a multi-step synchronization:
%       a. Matches experimental runs between the neural and audio data.
%       b. Rejects neural trials that are shorter than a 99% duration threshold.
%       c. Identifies the minimum common trial length (in samples)
%          across all valid neural and audio trials.
%   8.  **Finalize Data:** Appends data from all runs and truncates every
%       trial to the uniform minimum length, ensuring perfect temporal
%       alignment and matrix compatibility for decoding models.
%   9.  **Save Output:** Saves a single .mat file for the specified sensor
%       type, containing a results struct with the cleaned data and metadata.
%
% Syntax:
%   preprocessing_meeg_audiobooks_decoding(settings, subject, session)
%
% Inputs:
%   settings (struct):      A structure containing all analysis paths
%                           (e.g., BIDS root, derivatives, JSON metadata) 
%                           and parameters (e.g., filter settings, epoch duration).
%   subject (char/string):  The subject identifier (e.g., 'sub-01').
%   session (char/string):  The session identifier (e.g., 'ses-01').
%
% Outputs:
%   (None directly, saves a file to disk)
%   - A .mat file is saved to the subject's preprocessing directory, with a
%     filename dynamically generated based on subject, session, sensor type
%     and frequency band. The file contains a 'results' struct with the
%     following key fields:
%       .epochs_neuro:   Preprocessed neural data (FieldTrip data struct).
%       .epochs_audio:   Synchronized audio envelope for each trial (cell array).
%       .mapping_epochs: Start/end indices mapping trials back to their runs.
%       .mapping_label:  Label for each experimental run.
%       .settings:       The settings structure used for preprocessing 
%                        (including .min_dur).
%
%--------------------------------------------------------------------------

%% Script settings 
%--------------------------------------------------------------------------

% Taskname
% Extract session index for correct audiobook
ses_idx = str2double(regexp(session, '\d+', 'match', 'once'));
task    = sprintf('audiobook%i',ses_idx);

% Get selected sensors
cfg_sensors      = settings.cfg_sensors; % used for channel selection
sensors4analysis = settings.analysis.sensors;
n_sens           = length(sensors4analysis);

% Runs
runs   = [1,2];
n_runs = length(runs);

% Preprocessing settings
%--------------------------------------------------------------------------
use_maxfilter            = settings.use_maxfilter; % check whether maxfiltered data should be analyzed
use_ica                  = settings.use_ica; % check whether ica preprocessed data should be analyzed
apply_latency_correction = settings.apply_latency_correction; % Latency Correction
audio_latency            = settings.audio_latency;
interpolate_bad_channel  = settings.interpolate_bad_channel; % only affects EEG

% Filter settings
filtertype = settings.decoding.filtertype; % windowed sinc type I linear phase FIR filter
bpfreq     = settings.decoding.bpfreq; % meg + audio

trialdur   = settings.decoding.trialdur; % Epoch length
fs_down    = settings.decoding.fs_down; % Downsampling frequency
fs_neuro   = settings.decoding.fs_neuro; % MEG sampling frequency

%% Preprocessing 
%--------------------------------------------------------------------------

% Loop over different sensors
%--------------------------------------------------------------------------
for sens_idx = 1:n_sens % Loop over sensors / channels

    % Initialize data
    epochs_neuro   = cell(1,n_runs); % sensors x runs
    mapping_epochs = zeros(n_runs,2); % mapping between audiobooks and epoch trials (audiobooks x [begin end])
    mapping_labels = cell(1,n_runs); % contains audiobook labels

    f_idx         = 1; % file counter
    epoch_counter = 0; % epoch counter

    sensor = sensors4analysis{sens_idx};
    % MEG
    if strcmp(sensor, 'meg')
        channel = sensor;
    % EEG
    elseif strcmp(sensor, 'eeg')
        channel = unique([cfg_sensors.cap_eeg(:); cfg_sensors.ear_eeg.both(:)]);
        assert(numel(channel) == 76, 'Expected exactly 76 unique sensors, got %d', numel(channel));
    % Ear-EEG
    elseif strcmp(sensor, 'ear_eeg')
        channel = cfg_sensors.ear_eeg.both;
    % Biochannels
    elseif strcmp(sensor, 'biochannels')
        channel = settings.cfg_sensors.biochannels;
    else
        error('Unexpected sensor type: %s', sensor);
    end

    for run_idx = 1:n_runs % Loop over runs
    
        run = sprintf('run-0%i',runs(run_idx));
    
        % Define datapath
        %----------------
        if use_maxfilter && use_ica
            rawdata_path = fullfile(settings.path2ica(subject));
            filename     = sprintf('%s_%s_task-%s_%s_proc-ica_meg.fif',subject,session,task,run);
            data_path    = fullfile(rawdata_path,filename);

        elseif use_maxfilter && ~use_ica
            rawdata_path = fullfile(settings.path2derivatives,subject,'maxfilter');
            % Use movement-corrected data first if available
            if strcmp(subject,'sub-00')
                filename = sprintf('%s_%s_task-%s_%s_proc-tsss_meg.fif',subject,session,task,run); 
            else  
                filename = sprintf('%s_%s_task-%s_%s_proc-tsss-mc_meg.fif',subject,session,task,run); 
            end
            data_path    = fullfile(rawdata_path,filename);
    
        else
            rawdata_path = fullfile(settings.path2bids,subject,session,'meg');
            filename     = sprintf('%s_%s_task-%s_%s_meg.fif',subject,session,task,run);
            data_path    = fullfile(rawdata_path,filename);
            % badchannels  = settings.badchannels; 
           
        end

        % use bids data for events
        event_path = fullfile(settings.path2bids,subject,session,'meg',sprintf('%s_%s_task-%s_%s_meg.fif',subject,session,task,run));

        % Process data if it exists
        if isfile(data_path) 
        
            %% Define trials
            %---------------
            % based on fieldtrip events - searching in STI101 rather
            % than importing bids trigger
            cfg                     = [];
            cfg.trialfun            = 'my_trialfun_audiobook'; 
            cfg.dataset             = event_path; % path should always point to original bids-path
            cfg.trialdef.trialdur   = trialdur; 
            cfg.trialdef.eventvalue = 1;  
            % cfg.trialdef.method   = 'fieldtrip';
            % cfg.trialdef.eventtype  = 'STI101';
            cfg.trialdef.method     = 'bids';
            cfg.trialdef.eventtype  = {'audiobook 1s'};
            cfg                     = ft_definetrial(cfg);
        
            trl = cfg.trl;
    
            %% Add latency correction 
            %------------------------
            if apply_latency_correction
                trl(:,1:2) = trl(:,1:2) + round(audio_latency*1000); % in samples
            end

            %% Filter continuous data to avoid edge artifacts
            %------------------------------------------------
            cfg              = [];
            cfg.channel      = channel; 
            cfg.dataset      = data_path;
            cfg.bpfilter     = 'yes';
            cfg.bpfilttype   = filtertype;
            cfg.bpfreq       = bpfreq;
            cfg.plotfiltresp = 'no';
            data             = ft_preprocessing(cfg); 
    
            if ~isequal(data.fsample,fs_neuro)
                error('Unexpected sampling frequency for meg recordings (%i)!',data.fsample)
            end

            % plot spectrum
            %--------------
            % cfg         = [];
            % cfg.output  = 'pow';
            % cfg.method  = 'mtmfft';
            % cfg.taper   = 'hanning';
            % cfg.foi     = 0:100;    
            % spectr      = ft_freqanalysis(cfg,data);   
            % 
            % figure
            % plot(spectr.freq,db(spectr.powspctrm(:,:)))
            % xlabel('f / Hz')    
            % xlim([0,80])

            %% Apply bad channel interpolation
            %--------------------------------------------------------------
	        % - This should only be applied to maxfiltered or raw data, as 
            %   ICA-preprocessed data has already been interpolated in Python.
            % - This step exclusively affects EEG channels.
            % - Requires the list of bad channels detected during the 
            %   ICA pipeline and stored in a JSON metadata file.

            if ismember(sensor, {'eeg', 'ear_eeg'}) && interpolate_bad_channel && ~use_ica
    
                % Import bad channels from Python JSON metadata
                %----------------------------------------------
                fname2load   = fullfile(settings.path2ica(subject), sprintf('%s_metadata_proc-ica_meg.json', subject));
                jsonText     = fileread(fname2load);
                metadata_ica = jsondecode(jsonText);
                
                % Extract bad channels 
                % (Replacing hyphens with underscores to match valid MATLAB struct fields)
                session_field = strrep(session, '-', '_');
                fname_field   = strrep(sprintf('%s_%s', task, run), '-', '_');
                bad_channels  = metadata_ica.(session_field).bad_channels.(fname_field);
                 
                % Interpolate bad channels using spherical splines
                %-------------------------------------------------
                if ~isempty(bad_channels)
                    cfg            = [];
                    cfg.badchannel = intersect(channel, bad_channels); % bad channels that do occur
                    cfg.method     = 'spline';
                    cfg.senstype   = 'eeg';
                    data           = ft_channelrepair(cfg, data);
                end
                clear fname2load jsonText metadata_ica session_field fname_field bad_channels
            end

            %% Managing EEG channel reference
            %--------------------------------
            if strcmp(sensor, 'eeg')
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; % this is the default
                cfg.refchannel = 'all'; % average is computed over the channels specified in cfg.refchannel
                data           = ft_preprocessing(cfg,data);

            elseif strcmp(sensor, 'ear_eeg')
                % use avg ref instead of individual channels to make it
                % more robust
    
                % Left channels
                %--------------
                cfg         = []; 
                cfg.channel = cfg_sensors.ear_eeg.left;
                data_left   = ft_selectdata(cfg,data);
    
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; 
                % cfg.refchannel = 'EEG073'; 
                cfg.refchannel = 'all';
                data_left      = ft_preprocessing(cfg,data_left);
    
                % Right channels
                %---------------
                cfg         = []; 
                cfg.channel = cfg_sensors.ear_eeg.right;
                data_right  = ft_selectdata(cfg,data);
    
                cfg            = [];
                cfg.reref      = 'yes';
                cfg.refmethod  = 'avg';
                cfg.channel    = 'all'; 
                % cfg.refchannel = 'EEG074'; 
                cfg.refchannel = 'all';
                data_right     = ft_preprocessing(cfg,data_right);
    
                % Append data
                %------------
                cfg  = [];
                data = ft_appenddata(cfg,data_left,data_right);
    
                % Remove references
                %------------------
                % idx                = contains(channels,{'EEG073','EEG074'});
                % channels_both      = channels;
                % channels_both(idx) = [];
                % 
                % cfg         = [];
                % cfg.channel = channels_both;
                % data        = ft_selectdata(cfg,data);
                   
                clear data_left data_right 
            end

            %% Epoch data
            %------------
            cfg     = [];
            cfg.trl = trl;  
            epoch   = ft_redefinetrial(cfg,data);
            clear data
    
            % Set new offset for time: time 0 is the first trigger onset and
            % from there on the time moves forward in each trial. It 
            % doesn't start always from 0.
            cfg        = [];
            cfg.offset = trl(:,1)-trl(1,1);
            epoch      = ft_redefinetrial(cfg, epoch);   
    
            % Count epochs
            n_epochs                = length(epoch.trial);
            mapping_epochs(f_idx,:) = [epoch_counter+1,epoch_counter + n_epochs];
            epoch_counter           = epoch_counter + n_epochs;
            mapping_labels{f_idx}   = sprintf('task-%s_%s',task,run);

            %% Downsampling
            %--------------
            cfg                 = [];
            cfg.resamplefs      = fs_down;
            cfg.detrend         = 'no';
            epochs_neuro{f_idx} = ft_resampledata(cfg,epoch);
            % clear epoch

        end % file exists

        % Increment counter
        f_idx = f_idx + 1;

    end % loop over runs

    %% Import audio data
    %----------------------------------------------------------------------
    fname = sprintf(settings.fnames.audio_audiobook, settings.helper.formatFreqBand(bpfreq));
      
    audio            = importdata(fullfile(settings.path2derivatives,'stimuli',fname));
    epochs_audio     = audio.epochs_audio;
    audiobook_labels = audio.audiobook_labels;
    clear audio

    %% Append data over trials and correct for differences in number of trials and trial durations
    %---------------------------------------------------------------------------------------------
    % Keep only non-empty cells in case runs are missing
    nonEmptyIdx    = ~cellfun('isempty',mapping_labels);
    mapping_epochs = mapping_epochs(nonEmptyIdx,:);
    mapping_labels = mapping_labels(nonEmptyIdx);

    % Match audio and neuro runs
    [~, loc_idx]     = ismember(mapping_labels, audiobook_labels);
    epochs_audio     = epochs_audio(loc_idx);
    audiobook_labels = audiobook_labels(loc_idx);

    % Compare mapping between audio and neura data and continue only if identical
    check_mapping = isequal(mapping_labels,audiobook_labels);
    if ~check_mapping
        error('%s: Mismatch in mapping between neuro and audio files!');
    end

    % Remove additional audio trials & trials that are shorter than
    % trial_dur
    %----------------------------------------------------------------------
    n_files = length(epochs_neuro);
    
    epoch_counter = 0;
    min_dur       = inf; % minimal durations for trials
    for f_idx = 1:n_files
        % Audio is always longer than neuro due to experimental design of
        % trigger -> remove extra audio trials
        %------------------------------------------------------------------
        trials_neuro = epochs_neuro{f_idx}.trial;
        trials_audio = epochs_audio{f_idx}.trial;
        n_neuro      = length(trials_neuro);
    
        % Remove additional audio trials
        trials_audio = trials_audio(1:n_neuro);
    
        % Check duration for epochs that are shorter than 99% of trial_dur
        %------------------------------------------------------------------
        is_trial_valid = true(1,n_neuro);
        dur_expected   = fs_down*trialdur; % desired trial duration in samples
        for trl_idx = 1:n_neuro
            dur_neuro = size(trials_neuro{trl_idx},2);
            dur_audio = length(trials_audio{trl_idx}); % end column: audio
    
            % Condition 1: Trial is too short
            if dur_neuro < 0.99 * dur_expected   
                is_trial_valid(trl_idx) = false;
                continue; % Skip to the next trial
            end
    
            % Condition 2: Sanity check for audio/neuro async (arbitrary threshold)
            if abs(dur_neuro-dur_audio) > trialdur * 2
                error('%s: Mismatch in trial duration between audio and neuro is too large for trial %d.', subject, trl_idx);
            end
    
            % Update minimum duration
            min_dur = min([min_dur, dur_neuro, dur_audio]);
    
        end % loop over trials
    
        % Remove unwanted epochs
        %-----------------------
        epochs_audio{f_idx}.trial = trials_audio(is_trial_valid);
        epochs_audio{f_idx}.time  = epochs_audio{f_idx}.time(is_trial_valid);
        epochs_audio{f_idx}.trl   = epochs_audio{f_idx}.trl(is_trial_valid,:);
    
        cfg                 = [];
        cfg.trials          = is_trial_valid;
        epochs_neuro{f_idx} = ft_selectdata(cfg, epochs_neuro{f_idx});
    
        n_neuro = length(epochs_neuro{f_idx}.trial);
        n_audio = length(epochs_audio{f_idx}.trial);
        if ~isequal(n_neuro,n_audio)
            error('%s: Unexpected number of audio trials (%i) and neuro trials (%i)',subject,n_audio,n_neuro)
        end
    
        % Update mapping
        mapping_epochs(f_idx,:) = [epoch_counter+1,epoch_counter + n_neuro];
        epoch_counter           = epoch_counter + n_neuro; 
    
    end

    % Append data over all recordings
    %--------------------------------
    % Append MEG recordings
    cfg                = [];
    cfg.keepsampleinfo = 'no'; 
    epochs_neuro       = ft_appenddata(cfg, epochs_neuro{:});

    % Append Audio recordings
    epochs_audio_all = cell(1,length(epochs_audio));
    for f_idx = 1:n_files
        epochs_audio_all{f_idx} = epochs_audio{f_idx}.trial;
    end
    epochs_audio = [epochs_audio_all{:}];
    clear epochs_audio_all

    % Match length of trials
    %-----------------------
    n_trials = length(epochs_audio);
    
    for trl_idx = 1:n_trials
        epochs_neuro.trial{trl_idx} = epochs_neuro.trial{trl_idx}(:,1:min_dur);
        epochs_neuro.time{trl_idx}  = epochs_neuro.time{trl_idx}(1:min_dur);
        epochs_audio{trl_idx}       = epochs_audio{trl_idx}(1:min_dur);
    end

    %% Save results
    %--------------
    dir2save = settings.path2decoding_preprocessing(subject);
    if ~exist(dir2save,'dir')
        mkdir(dir2save)
    end
    fname = sprintf(settings.fnames.preprocessed_audiobooks,subject,session,sensor,settings.helper.formatFreqBand(bpfreq));  
    
    results                = struct;
    results.settings       = settings;
    settings.min_dur       = min_dur;
    results.epochs_neuro   = epochs_neuro;
    results.epochs_audio   = epochs_audio;
    results.mapping_epochs = mapping_epochs;
    results.mapping_label  = mapping_labels;
    
    save(fullfile(dir2save,fname),'results','-v7.3'); 
    fprintf("\n%s from %s saved.\n",fname,subject)
end % Loop over senors

end % function