function [stats] = compute_statistic_concatenated_trials(y, pred, n_comb, dim, corr_metric, circ_shift, fs_audio, shift_target)
%--------------------------------------------------------------------------
% Till Habersetzer, 17.09.2025
% Communication Acoustics, CvO University Oldenburg
% till.habersetzer@uol.de 
%
%   Revision History:
%   14.05.2026 - Added optional 'shift_target' parameter to allow shifting 
%                of either the 'audio' or 'prediction' signals. 
%                Default fallback added for backward compatibility.
%
%   Description:
%   Computes a bootstrap distribution of a correlation metric and also
%   calculates the 'true' observed statistic on the original, non-resampled
%   data. This allows for direct comparison of the observed value against
%   the bootstrap distribution to assess its stability and significance.
%
%   The bootstrap distribution is generated by creating `n_comb` new datasets.
%   Each dataset is formed by drawing N trials with replacement from the
%   original pool of N trials. The pairing between `y{k}` and `pred{k}` is
%   always preserved. An optional circular shift can be applied to either 
%   the `pred` or `y` trials for an additional layer of randomization.
%
%   Inputs:
%   y             (cell array):  1xN cell array of ground truth data.
%   pred          (cell array):  1xN cell array of predicted data.
%   n_comb        (integer):     Number of bootstrap samples to generate.
%   dim           (integer):     Dimension for the evaluation function (e.g., 1 or 2).
%   corr_metric   (string):      Correlation metric, e.g., 'Pearson' or 'Spearman'.
%
%   Optional Inputs:
%   circ_shift    (logical):     If true, applies a random circular shift to each
%                                selected trial. Default: false.
%   fs_audio      (integer):     Sampling frequency (Hz). If provided and circ_shift
%                                is true, the shift will be at least 1 second.
%   shift_target  (string):      Specifies which signal to shift: 'prediction' or 'audio'.
%                                Default: 'prediction'.
%
%   Outputs:
%   stats         (struct):      A structure containing the analysis results.
%     .r_orig       (scalar):  The correlation score for the original, non-resampled data.
%     .r            (vector):  A 1-by-n_comb vector of correlation scores from bootstrap samples.
%     .err          (vector):  A 1-by-n_comb vector of error scores from bootstrap samples.
%     .r_mean       (scalar):  The mean of the bootstrap distribution.
%     .r_std        (scalar):  The standard deviation of the bootstrap distribution.
%     .r_prctile    (vector):  Percentiles [2.5, 25, 50, 75, 97.5] of the bootstrap distribution.
%     .n_comb_used  (scalar):  The number of combinations run.
%
%--------------------------------------------------------------------------

% Handle optional arguments (ensure backward compatibility)
if nargin < 8 || isempty(shift_target)
    shift_target = 'prediction';
else
    % Validate that the provided shift_target is strictly 'audio' or 'prediction'
    if ~any(strcmpi(shift_target, {'audio', 'prediction'}))
        error('Invalid shift_target: ''%s''. Must be either ''audio'' or ''prediction''.', shift_target);
    end
end
if nargin < 7 || isempty(fs_audio)
    fs_audio = []; 
end
if nargin < 6 || isempty(circ_shift)
    circ_shift = false;
end

% Ensure all cell entries are 1xN row vectors for consistent indexing
pred = cellfun(@(x) x(:).', pred, 'UniformOutput', false);
y    = cellfun(@(x) x(:).', y,    'UniformOutput', false);

% This ensures the cell array is a 1xN row, not an Nx1 column.
pred = pred(:).';
y    = y(:).';

% Get the total number of trials available
n_trials = length(y);
if n_trials ~= length(pred)
    error('The number of trials in y and pred must be the same!');
end

% Initialize data structure for correlation values and errors
r   = zeros(1, n_comb); 
err = zeros(1, n_comb);

% Pre-calculate trial lengths for the circshift operation if needed
if circ_shift
    if strcmpi(shift_target, 'audio')
        trial_lengths = cellfun(@length, y);
    else
        trial_lengths = cellfun(@length, pred);
    end
end

% Define the interval for progress updates (every 10%)
update_step = max(1, floor(n_comb / 10));

%% Compute Combinations
%--------------------------------------------------------------------------
fprintf('Running %d combinations...\n', n_comb);

% Compute all combinations
%-------------------------
% Generates an [n_comb x n_trials] matrix of random indices for bootstrapping 
% (sampling with replacement)
combinations = randi(n_trials, n_comb, n_trials);

% Loop over each combination and compute the correlation 
%--------------------------------------------------------------------------
for c_idx = 1:n_comb
        
    % Get the indices for the current combination of trials
    trial_indices = combinations(c_idx, :);

    % Assemble concatenated data for this combination 
    %------------------------------------------------
    if circ_shift
        % Slower path: Must loop to apply circshift to each segment
        target_segments = cell(1, n_trials);

        for trl_idx = 1:n_trials
            selection_idx = trial_indices(trl_idx);
            
            % Select the target variable to shift based on input
            if strcmpi(shift_target, 'audio')
                target_trial = y{selection_idx};
            else
                target_trial = pred{selection_idx};
            end
            
            len = trial_lengths(selection_idx);
            
            if len > 1
                if ~isempty(fs_audio) && len > fs_audio
                    idx_shift = randi([fs_audio, len - 1]);
                else
                    idx_shift = randi(len - 1);
                end
                target_segments{trl_idx} = circshift(target_trial, idx_shift, 2);
            else
                target_segments{trl_idx} = target_trial;
            end
        end
        
        % Assign concatenated target segments to the correct output
        if strcmpi(shift_target, 'audio')
            y_concat    = [target_segments{:}];
            pred_concat = [pred{trial_indices}];
        else
            pred_concat = [target_segments{:}];
            y_concat    = [y{trial_indices}];
        end
    else
        % Fast path: No circular shift, so concatenate directly
        pred_concat = [pred{trial_indices}];
        y_concat    = [y{trial_indices}];
    end
  
    % Perform the correlation computation
    %----------------------------------------------------------------------
    [r(c_idx), err(c_idx)] = mTRFevaluate(y_concat, pred_concat, 'dim', dim, 'corr', corr_metric);

    % Update progress indicator
    %----------------------------------------------------------------------
    % Check if the current iteration is an update point or the very last one.
    if mod(c_idx, update_step) == 0 || c_idx == n_comb
        fprintf('\nProcessed %d / %d combinations.', c_idx, n_comb);
    end
end % Loop over permutations

fprintf('\nStatistical analysis complete.\n');

% Add special case when all data is concatenated without resampling
%--------------------------------------------------------------------------
epochs_concat = [y{:}];
pred_concat   = [pred{:}];

[r_orig, ~] = mTRFevaluate(epochs_concat, ...
                           pred_concat,...
                           'dim',dim,...
                           'corr',corr_metric);

% Package results into the output struct
%--------------------------------------------------------------------------
% Compute and store summary statistics for this subset size 
stats              = struct();
stats.r_orig       = r_orig;
stats.r            = r;
stats.err          = err;
stats.r_mean       = mean(r);
stats.r_std        = std(r);
stats.r_prctile    = prctile(r, [2.5, 25, 50, 75, 97.5]);
stats.n_comb_used  = n_comb;

end % End of main function